import type { Metadata } from "next";
import { Entrance } from "./components/entrance/Entrance";
import styles from "./page.module.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export default function Home() {
  return (
    <div className={styles.page}>
      <Entrance/>
    </div>
  );
}
